# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - azure-dns-updater

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x' # set this to the dotnet version to use
  FUNCTION_APP: func-dyndns-test
  RESOURCE_GROUP: rg-dyndns-test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: # ${{ secrets.AZURE_CREDENTIALS }}
          tenant-id: ${{ secrets.AZURE_TENANT }}
          # Azure subscriptionId
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
          
      - name: Open firewall
        uses: Azure/cli@v1.0.7
        with:
          # Specify the script here
          inlineScript: 
            az account set -s '${{ secrets.AZURE_SUBSCRIPTION }}'
            az functionapp config access-restriction add -g ${{ env.RESOURCE_GROUP }} -n ${{ env.FUNCTION_APP }} --scm-site true --rule-name AllowAzureCloud --service-tag AzureCloud --priority 300 --action Allow -o none

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.FUNCTION_APP }}
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6C31E99A562242A6BCE56A3651C2A70A }}
    
      - name: Open firewall
        uses: Azure/cli@v1.0.7
        with:
          # Specify the script here
          inlineScript:
            az account set -s '${{ secrets.AZURE_SUBSCRIPTION }}'
            az functionapp config access-restriction remove -g ${{ env.RESOURCE_GROUP }} -n ${{ env.FUNCTION_APP }} --scm-site true --rule-name AllowAzureCloud --service-tag AzureCloud --priority 300 --action Allow -o none
